language: c
env:
  - TOOL_NAME=terraform-docs TOOL_VERSION=v0.6.0 TOOL_TEST_COMMAND='terraform-docs --version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - ./shellcheck-on-linux-only.sh
  - asdf plugin-add $TOOL_NAME ./
  - asdf list-all $TOOL_NAME
  - asdf plugin-test $TOOL_NAME ./ "$TOOL_TEST_COMMAND" --asdf-tool-version $TOOL_VERSION
os:
  - linux
  - osx
